"""add start_date and end_date to works, addres

Revision ID: 33ad535fe7b5
Revises: 2854b0e65daf
Create Date: 2024-12-10 20:04:39.109150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33ad535fe7b5'
down_revision: Union[str, None] = '2854b0e65daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('photos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('observations', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('activities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('work_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.add_column('works', sa.Column('name', sa.String(), nullable=False))
    op.add_column('works', sa.Column('zip_code', sa.String(), nullable=False))
    op.add_column('works', sa.Column('state', sa.String(), nullable=False))
    op.add_column('works', sa.Column('neighborhood', sa.String(), nullable=False))
    op.add_column('works', sa.Column('public_place', sa.String(), nullable=False))
    op.add_column('works', sa.Column('number_addres', sa.String(), nullable=True))
    op.add_column('works', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('works', sa.Column('end_date', sa.Date(), nullable=True))
    op.drop_column('works', 'observations')
    op.drop_column('works', 'photos')
    op.drop_column('works', 'activities')
    op.drop_column('works', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('works', sa.Column('activities', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('works', sa.Column('photos', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('works', sa.Column('observations', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.drop_column('works', 'end_date')
    op.drop_column('works', 'start_date')
    op.drop_column('works', 'number_addres')
    op.drop_column('works', 'public_place')
    op.drop_column('works', 'neighborhood')
    op.drop_column('works', 'state')
    op.drop_column('works', 'zip_code')
    op.drop_column('works', 'name')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
