"""Adicionado created_at e updated_at no model do rentequipment

Revision ID: 83b1cd0f7230
Revises: f9e77e602fde
Create Date: 2024-12-06 21:10:05.685653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83b1cd0f7230'
down_revision: Union[str, None] = 'f9e77e602fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rents-equipments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('rents-equipments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rents-equipments', 'updated_at')
    op.drop_column('rents-equipments', 'created_at')
    # ### end Alembic commands ###
