"""initial migration

<<<<<<<< HEAD:backend/alembic/versions/e6952ee01015_initial_migration.py
Revision ID: e6952ee01015
Revises: 1d03c6da711d
Create Date: 2024-12-17 20:38:11.801819
========
Revision ID: 93d58b9647d7
Revises: 
Create Date: 2025-01-30 21:52:27.703920
>>>>>>>> mergeConflitos2:backend/alembic/versions/93d58b9647d7_initial_migration.py

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d58b9647d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
