"""initial migration

Revision ID: fec9310e009c
Revises: 
Create Date: 2024-12-16 21:42:45.949522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fec9310e009c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersassociation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('work_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersassociation_id'), 'usersassociation', ['id'], unique=False)
    op.drop_index('ix_user_works_associations_id', table_name='user_works_associations')
    op.drop_table('user_works_associations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_works_associations',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('work_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_works_associations_user_id_fkey'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], name='user_works_associations_work_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_works_associations_pkey')
    )
    op.create_index('ix_user_works_associations_id', 'user_works_associations', ['id'], unique=False)
    op.drop_index(op.f('ix_usersassociation_id'), table_name='usersassociation')
    op.drop_table('usersassociation')
    # ### end Alembic commands ###
